version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: photopea_app_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  photopea:
    image: photopea/photopea-selfhosted:latest
    restart: unless-stopped
    ports:
      - "8487:80"
